<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import ros2_control -->
  <xacro:include filename="$(find myactuator_rmd_description)/urdf/myactuator_rmd.ros2_control.xacro" />

  <!-- Macro for inertia matrix for cylinder around its center -->
  <xacro:macro name="cylinder_inertial" params="m x y z radius height">
    <inertial>
      <mass value="${m}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <inertia ixx="${1/12*m*height*height}" ixy="0.0" ixz="0.0"
                iyy="${1/12*m*height*height}" iyz="0.0"
                izz="${1/2*m*radius*radius}"/>
    </inertial>
  </xacro:macro>

  <!-- Actuator geometry -->
  <xacro:macro name="myactuator_rmd" params="name parent_link child_link joint_name
                                             simulation ifname actuator_id visual
                                             radius_1 height_1
                                             radius_2 height_2
                                             radius_3 height_3 mass">
    
    <!-- Compute the inertial properties of the different parts of the actuator assuming uniform density -->
    <xacro:property name="volume_1" value="${radius_1*radius_1*pi*height_1}"/>
    <xacro:property name="volume_2" value="${radius_2*radius_2*pi*height_2}"/>
    <xacro:property name="volume_3" value="${radius_3*radius_3*pi*height_3}"/>
    <xacro:property name="volume_1_2_3" value="${volume_1+volume_2+volume_3}"/>
    <xacro:property name="mass_1" value="${volume_1/volume_1_2_3*mass}"/>
    <xacro:property name="mass_2" value="${volume_2/volume_1_2_3*mass}"/>
    <xacro:property name="mass_3" value="${volume_3/volume_1_2_3*mass}"/>

    <link name="${name}">
      <visual>
        <geometry>
          <mesh filename="file://${visual}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${height_1/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${height_1}" radius="${radius_1}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial m="${mass_1}" x="0" y="0" z="${height_1/2}" 
                               radius="${radius_1}" height="${height_1}"/>
    </link>

    <joint name="${parent_link}_to_${name}" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${parent_link}" />
      <child link="${name}" />
    </joint>

    <link name="${name}_body">
      <collision>
        <origin xyz="0 0 ${height_2/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${height_2}" radius="${radius_2}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial m="${mass_2}" x="0" y="0" z="${height_2/2}" 
                               radius="${radius_2}" height="${height_2}"/>
    </link>

    <joint name="${name}_to_${name}_body" type="fixed">
      <origin xyz="0 0 ${height_1}" rpy="0 0 0" />
      <parent link="${name}" />
      <child link="${name}_body" />
    </joint>

    <link name="${name}_shaft">
      <collision>
        <origin xyz="0 0 ${height_3/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${height_3}" radius="${radius_3}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial m="${mass_3}" x="0" y="0" z="${height_3/2}" 
                               radius="${radius_3}" height="${height_3}"/>
    </link>

    <joint name="${joint_name}" type="revolute">
      <origin xyz="0 0 ${height_2}" rpy="0 0 0" />
      <parent link="${name}_body" />
      <child link="${name}_shaft" />
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="${-pi}" upper="${pi}" velocity="2.0"/>
    </joint>

    <joint name="${name}_to_${name}_shaft" type="fixed">
      <origin xyz="0 0 ${height_3}" rpy="0 0 0" />
      <parent link="${name}_shaft" />
      <child link="${child_link}" />
    </joint>

    <!-- ros2_control configuration -->
    <xacro:myactuator_rmd_ros2_control name="${joint_name}_ros2_control" joint_name="${joint_name}" simulation="${simulation}"
                                       ifname="${ifname}" actuator_id="${actuator_id}"/>
  </xacro:macro>

</robot>